# .github/workflows/building-sphinx-docs.yml
name: Build Sphinx Docs

env:
  BRANCH: dev-v1.0

on:
  push:
    branches:
      - dev-v1.0
    paths:
      - "docs/document-ja/source/**"
      - "docs/document-en/source/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/document-ja/requirements.txt
        pip install -r docs/document-en/requirements.txt

    - name: Build Sphinx documentation
      run: |
        echo "Build Japanese."
        cd docs/document-ja/
        make html
        echo "Build English."
        cd ../../docs/document-en/
        make html

    - name: Confirmation git status
      run: |
        git branch
        git diff --name-only

    - name: Deploy documentation to branch
      if: github.ref == 'refs/heads/$BRANCH'  # デプロイを行うブランチを指定
      run: |
        cd docs/_build/html
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git init
        git add .
        git commit -m "Commit the sphinx documentation build html"
        git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:$BRANCH
