# .github/workflows/docs-build-deployments.yml
name: Deploy Sphinx Docs to GitHub Pages

env:
  DOC_DIR: docs/document-ja

on:
  push:
    branches:
      - dev-v1.0
    paths:
      - "$DOC_DIR/source/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx_rtd_theme

    - name: Build Sphinx documentation
      run: |
        cd $DOC_DIR
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: dev-v1.0
        publish_dir: ./$DOC_DIR/_build/html
