# .github/workflows/docs-build-deployments.yml
name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build Sphinx documentation
      run: |
        git diff --name-only origin/main
        if git diff --name-only origin/main | grep '^docs/document-ja/source/'; then
          echo "Build Japanese."
          cd docs/document-ja
          pip install -r requirements.txt
          make html
        fi
        if git diff --name-only origin/main | grep '^docs/document-en/source/'; then
          echo "Build English."
          cd docs/document-en
          pip install -r requirements.txt
          make html
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs
