# .github/workflows/docs-build-deployments.yml
name: Deploy Sphinx Docs to GitHub Pages

env:
  DOC_DIR: docs/document-ja

on:
  push:
    branches:
      - main
    paths:
      - "$DOC_DIR/source/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $DOC_DIR/requirements.txt

    - name: Build Sphinx documentation
      run: |
        cd $DOC_DIR
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./$DOC_DIR/_build/html
